// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cryxrahpjbqauwmteyvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyeXhyYWhwamJxYXV3bXRleXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzgzNzMsImV4cCI6MjA3MjcxNDM3M30.56gur4oxSbR01aF_vb1hFi8LNjgriNkFeObI9OUCEGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});